"""Create the `_synthetic-example` run so the website has something to render.

This is fake data. It exists only so the charts, the run table and the index can
be developed and reviewed before the first real training run finishes. Its
config carries `"synthetic": true`, which is how the site knows to label it.

It deliberately does not write `policy.json`. There is no trained policy yet, so
the demo page correctly falls back to the random agent.

    python3 rl/tools/make_synthetic_run.py

Rerunning it overwrites the run and produces identical numbers, because the
random number generator is seeded.
"""

from __future__ import annotations

import json
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

from logger import DEFAULT_RUNS_DIR, METRICS_FILENAME  # type: ignore[import-not-found]

RUN_NAME = "_synthetic-example"
EPISODES = 30
SEED = 7

CONFIG = {
    "synthetic": True,
    "env": "CartPole-v1",
    "algorithm": "REINFORCE",
    "episodes": EPISODES,
    "learning_rate": 0.01,
    "gamma": 0.99,
    "hidden_size": 128,
    "optimizer": "Adam",
    "seed": SEED,
    "note": "Generated by rl/tools/make_synthetic_run.py. Not a real training run.",
}

NOTES = """# _synthetic-example

Fake run. Thirty episodes of made up rewards and losses, generated by
`rl/tools/make_synthetic_run.py` so the website has data to render before real
training exists.

There is no `policy.json` here on purpose, so the demo page falls back to the
random agent. Delete this run once real runs are in place.
"""


def main() -> Path:
    rng = random.Random(SEED)
    run_dir = DEFAULT_RUNS_DIR / RUN_NAME
    run_dir.mkdir(parents=True, exist_ok=True)

    config = {"run_name": RUN_NAME, "created_at": "2026-09-26T12:00:00Z", **CONFIG}
    with open(run_dir / "config.json", "w", encoding="utf-8") as handle:
        json.dump(config, handle, indent=2)
        handle.write("\n")

    start = datetime(2026, 9, 26, 12, 0, 0, tzinfo=timezone.utc)
    with open(run_dir / METRICS_FILENAME, "w", encoding="utf-8") as handle:
        for episode in range(EPISODES):
            progress = episode / (EPISODES - 1)
            # A learning curve: slow start, faster middle, noisy throughout.
            trend = 18.0 + 68.0 * progress**1.4
            reward = max(8.0, round(trend + rng.gauss(0.0, 8.0)))
            # REINFORCE losses swing either side of zero and shrink as the
            # policy sharpens.
            loss = rng.gauss(0.0, 1.0) * (1.4 - 0.85 * progress)
            timestamp = (start + timedelta(seconds=round(3.2 * episode + reward * 0.05))).isoformat().replace("+00:00", "Z")
            record = {
                "episode": episode,
                "reward": float(reward),
                "loss": round(loss, 6),
                "timestamp": timestamp,
            }
            handle.write(json.dumps(record) + "\n")

    with open(run_dir / "notes.md", "w", encoding="utf-8") as handle:
        handle.write(NOTES)

    print(f"wrote {EPISODES} synthetic episodes to {run_dir}")
    return run_dir


if __name__ == "__main__":
    main()
